### ISSUE TITLE
problem with creating conda env with flash2

### ISSUE THREAD

**Issue by balathl** [dstreett/FLASH2#10]
Hi,

I am trying to build a pipeline which includes flash2. The git available for flash2 currently has some issues. Is it possible to provide a tarball for flash2 which can be used to include in conda env as below:

https://conda.io/docs/user-guide/tutorials/build-pkgs.html
 
The attempts that i made were:
conda-build flash2
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for flash2
INFO:conda_build.metadata:Attempting to finalize metadata for flash2
BUILD START: [u'flash2-2.2.00-0.tar.bz2']
Cloning into '/root/anaconda/conda-bld/flash2_1517590357585/work'...
done.
checkout: u'v2.2.00'
error: pathspec 'v2.2.00' did not match any file(s) known to git.
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was:
Command '['/usr/bin/git', 'checkout', 'v2.2.00']' returned non-zero exit status 1
Failed to download or patch source. Please see build log for info.

Below is my meta.yaml file content:
################## meta.yaml ##################################
package:
  name: flash2
  version: "2.2.00"

source:
  git_rev: v2.2.00
  git_url: https://github.com/dstreett/FLASH2.git

requirements:
  build:
   
  run:

test:
  imports:

about:
  home: https://github.com/dstreett/FLASH2
  license: BSD
  license_file: LICENSE
######################build.sh#################################
$PYTHON setup.py install --single-version-externally-managed --record=record.txt  # Python command to install the script.
######################bld.bat###################################
"%PYTHON%" setup.py install --single-version-externally-managed --record=record.txt
if errorlevel 1 exit 1

All the above three files were in flash2 folder created and the command executed was:

conda-build flash2

Error i got is below:

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for flash2
INFO:conda_build.metadata:Attempting to finalize metadata for flash2
BUILD START: [u'flash2-2.2.00-0.tar.bz2']
Cloning into '/root/anaconda/conda-bld/flash2_1517590750211/work'...
done.
checkout: u'v2.2.00'
error: pathspec 'v2.2.00' did not match any file(s) known to git.
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/git', 'checkout', 'v2.2.00']' returned non-zero exit status 1
Failed to download or patch source. Please see build log for info.

Hope you can help to make flash2 available/compatible with conda env!!

Bala

**Comment by msettles** [comment]
Hello Bala,


I have no idea what this entails, but I took a guess that its looking for a release and so I’ve created one. You may need to change the version to 2.2.00 dropping the ‘v’.

 

But give it try and let us know

Matt

**Comment by balathl** [comment]
Hi,

Thanks for your quick response! I rerun the code but now ended up in slightly different error as below:

# conda-build flash2
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for flash2
INFO:conda_build.metadata:Attempting to finalize metadata for flash2
BUILD START: [u'flash2-2.2.00-0.tar.bz2']
From https://github.com/dstreett/FLASH2
 * [new tag]         2.2.00     -> 2.2.00
Cloning into '/root/anaconda/conda-bld/
flash2_1518095364537/work'...
done.
checkout: u'2.2.00'
Note: checking out '2.2.00'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 64826f4... Merge pull request #7 from dstreett/develop
==> git log -n1 <==

commit 64826f4574b11b3c0ae7460826f30be16f49c3ea
Merge: 55e230f 288e1f0
Author: David Streett <davidastreett@hotmail.com<mailto:davidastreett@hotmail.com>>
Date:   Fri May 6 15:45:53 2016 -0700

    Merge pull request #7 from dstreett/develop

    Develop

==> git describe --tags --dirty <==

2.2.00

==> git status <==

HEAD detached at 2.2.00
nothing to commit, working directory clean

source tree in: /root/anaconda/conda-bld/flash2_1518095364537/work
/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh: line 56: setup.py: command not found
Traceback (most recent call last):
  File "/root/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1240, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/root/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/root/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh']' returned non-zero exit status 127



I tried to contact the conda developer as well as it might be from conda as well. But if you think the error might be from your side then feel free to provide some solution.

Best Regards,
Bala
________________________________

**Comment by msettles** [comment]
Bala, I use Anaconda to manage my python environment,  flash2 is C code,  0
python what I see below is that conda-build is  looking for setup.py a file
used to build python programs.  so it may be that conda-build it's intended
only gl for python apps (I know nothing about comda-build) and it's not for
c programs.

if the developers say otherwise and propose a solution let me knew.

Matt

On Feb 8, 2018 2:22 AM, "balathl" <notifications@github.com> wrote:

Hi,

Thanks for your quick response! I rerun the code but now ended up in
slightly different error as below:

# conda-build flash2

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for flash2
INFO:conda_build.metadata:Attempting to finalize metadata for flash2
BUILD START: [u'flash2-2.2.00-0.tar.bz2']
From https://github.com/dstreett/FLASH2
* [new tag] 2.2.00 -> 2.2.00
Cloning into '/root/anaconda/conda-bld/
flash2_1518095364537/work'...
done.
checkout: u'2.2.00'
Note: checking out '2.2.00'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b new_branch_name

HEAD is now at 64826f4... Merge pull request #7 from dstreett/develop
==> git log -n1 <==

commit 64826f4574b11b3c0ae7460826f30be16f49c3ea
Merge: 55e230f 288e1f0
Author: David Streett <davidastreett@hotmail.com<mailto:
davidastreett@hotmail.com>>
Date: Fri May 6 15:45:53 2016 -0700

Merge pull request #7 from dstreett/develop

Develop

==> git describe --tags --dirty <==

2.2.00

==> git status <==

HEAD detached at 2.2.00
nothing to commit, working directory clean

source tree in: /root/anaconda/conda-bld/flash2_1518095364537/work
/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh: line 56:
setup.py: command not found
Traceback (most recent call last):
File "/root/anaconda/bin/conda-build", line 11, in <module>
sys.exit(main())
File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py",
line 413, in main
execute(sys.argv[1:])
File "/root/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py",
line 404, in execute
verify=args.verify)
File "/root/anaconda/lib/python2.7/site-packages/conda_build/api.py", line
193, in build
need_source_download=need_source_download, config=config, variants=variants)
File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py",
line 1944, in build_tree
notest=notest,
File "/root/anaconda/lib/python2.7/site-packages/conda_build/build.py",
line 1240, in build
utils.check_call_env(cmd, env=env, cwd=src_dir)
File "/root/anaconda/lib/python2.7/site-packages/conda_build/utils.py",
line 678, in check_call_env
return _func_defaulting_env_to_os_environ(subprocess.check_call,
*popenargs, **kwargs)
File "/root/anaconda/lib/python2.7/site-packages/conda_build/utils.py",
line 674, in _func_defaulting_env_to_os_environ
return func(_args, **kwargs)
File "/root/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-e',
'/root/anaconda/conda-bld/flash2_1518095364537/work/conda_build.sh']'
returned non-zero exit status 127



I tried to contact the conda developer as well as it might be from conda as
well. But if you think the error might be from your side then feel free to
provide some solution.

Best Regards,
Bala
________________________________

**Comment by balathl** [comment]
Dear Matt,

I made the flash2 available in anaconda with your release with the below code. Now it can be integrated into some pipelines easily with conda env too. Thanks for your quick response on the release.



#####################################################################################
cat meta.yaml
{% set name = "flash2" %}
{% set version = "2.2.00" %}
{% set build = 0 %}
{% set hash = "7bb357a935de87be8a294b35ed281eca2e08afa1e1a1d1b1c24a024b80b713ff" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://github.com/dstreett/FLASH2/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: {{ build }}
  script: make

requirements:
  build:
    - python
    - make

test:
  commands:
    - /root/anaconda/conda-bld/flash2_1518176363321/work_moved_flash2-2.2.00-0_linux-64/flash2 --help

about:
  home: https://github.com/dstreett/FLASH2
  summary: FLASH is a tool to merge paired-end reads generated from DNA fragments
  #license: [the repos license (which doesn't exist)]
#license_file: [you should create a LICENSE file since the repo has none]


conda-build flash2 #flash2 is folder containing meta.yaml file

anaconda upload /root/anaconda/conda-bld/linux-64/flash2-2.2.00-0.tar.bz2

####################################################################################

Bala


________________________________
